%% Mission - Story/Excursion clickable variables, coordinates, descriptions
%%%%%%%%%%%%%%%%% Static array - Lobby - SubStory
var storyNum : int := 9 % 0-9. Start at 0
var storyN : array 0 .. storyNum of string
var storyD : array 0 .. storyNum of string
var storyC : array 0 .. storyNum, 0 .. 1 of int     % Main story chapter diamonds - X and Y
for sC : 0 .. 9     %% Main Story coordinate (Chapter I - X)
    storyC (sC, 0) := 149 + (300 * sC)
    storyC (sC, 1) := 409     %% Y coordinate
end for
storyNum := 0 % Reset to 0 for New Game
%%%%%%%%%%%%%%%%% Static array - Lobby - SubStory
var subSNum : int := 25 % 0-25. This is 26 total
var subStoryN : array 0 .. subSNum of string
var subStoryD : array 0 .. subSNum of string
var subStoryC : array 0 .. subSNum, 0 .. 1 of int
subSNum := -1 % Reset to -1 for New Game
%%%%%%%%%%%%%%%%% Static Array - Lobby - Excursion
var excNum : int := 24 % 0-24.  This is 25 total
var excursionN : array 0 .. excNum of string
var excursionD : array 0 .. excNum of string
var excursionC : array 0 .. excNum, 0 .. 1 of int
excNum := 0 % Reset to -1 for New Game

%%%%%%%%%%%%%%%%%% MAIN STORY
storyN (0) := 'I. Powerless'
storyD (0) := 'an unfamiliar place'
storyN (1) := 'II. Maze'
storyD (1) := 'one door in, ninety nine doors out'
storyN (2) := 'III. Escape'
storyD (2) := 'into another world'
storyN (3) := 'IV. Up'
storyD (3) := 'only one direction to go'
storyN (4) := 'V. Palace'
storyD (4) := 'shrouded in mystery, there lies a floating palace'
storyN (5) := 'VI. Hall'
storyD (5) := 'winding, twisting, where does it lead?'
storyN (6) := 'VII. Bomb'
storyD (6) := "external forces are acting"
storyN (7) := 'VIII. Clone'
storyD (7) := 'an impossible occurence points to one possibility'
storyN (8) := 'IX. Hints'
storyD (8) := 'follow the echoes of the machine'
storyN (9) := 'X. Simulation'
storyD (9) := 'unravel the truth behind this world'
%%%%%%%%%%%%%%%%%% SUBSTORY
subStoryN (0) := 'I - I. Blue'
subStoryD (0) := 'Discover the origins of Blue'
subStoryC (0, 0) := 253
subStoryC (0, 1) := 409
subStoryN (1) := 'I - II. July'
subStoryD (1) := 'Discover the origins of July'
subStoryC (1, 0) := 342
subStoryC (1, 1) := 408
subStoryN (2) := ' II - I. Left route'
subStoryD (2) := 'The trio chooses the left pathway.. where will it lead?'
subStoryC (2, 0) := 510
subStoryC (2, 1) := 528
subStoryN (3) := 'II - II. Coin flip'
subStoryD (3) := 'The next decision is decided by chance'
subStoryC (3, 0) := 550
subStoryC (3, 1) := 597
subStoryN (4) := 'II - II A. Upwards spiral'
subStoryD (4) := 'Dragon decides the way must be up'
subStoryC (4, 0) := 617
subStoryC (4, 1) := 671
subStoryN (5) := 'II - III. Mirror'
subStoryD (5) := 'A final puzzle - each path looks the same'
subStoryC (5, 0) := 592
subStoryC (5, 1) := 486
subStoryN (6) := 'III - I. Plains of Emeroth'
subStoryD (6) := 'The trio emerges onto a lush, bountiful plain. Flat as the eye can see'
subStoryC (6, 0) := 842
subStoryC (6, 1) := 499
subStoryN (7) := 'III - II. Long road'
subStoryD (7) := 'A road appears on the plains. Might as well follow it!'
subStoryC (7, 0) := 902
subStoryC (7, 1) := 529
subStoryN (8) := 'III - III. Campfire ambush'
subStoryD (8) := 'The trio is not alone.'
subStoryC (8, 0) := 962
subStoryC (8, 1) := 599
subStoryN (9) := 'IV - I. Sky bridge'
subStoryD (9) := 'The trio finds a rift in the ground, with only one bridge connecting the two sides'
subStoryC (9, 0) := 1145
subStoryC (9, 1) := 530
subStoryN (10) := 'IV - II. Stairway to the clouds'
subStoryD (10) := 'The mist clears and an infinitely long stairway fades in'
subStoryC (10, 0) := 1246
subStoryC (10, 1) := 509
subStoryN (11) := 'V - I. Silver gate'
subStoryD (11) := 'The trio ascends to the top and finds the silver gates of a palace'
subStoryC (11, 0) := 1444
subStoryC (11, 1) := 635
subStoryN (12) := 'V - II. Outer garden'
subStoryD (12) := 'A ringed fortress of shrub lies in front of the trio'
subStoryC (12, 0) := 1507
subStoryC (12, 1) := 566
subStoryN (13) := 'V - II A. Inner garden'
subStoryD (13) := 'The sky brightens in the center ring of the garden'
subStoryC (13, 0) := 1609
subStoryC (13, 1) := 567
subStoryN (14) := 'VI - I. The long hall'
subStoryD (14) := 'The trio ventures the seemingly endless hall'
subStoryC (14, 0) := 1746
subStoryC (14, 1) := 621
subStoryN (15) := 'VI - II. Serpent'
subStoryD (15) := 'Out of the darkness, a Kemoyin strikes!'
subStoryC (15, 0) := 1797
subStoryC (15, 1) := 526
subStoryN (16) := 'VI - III. Shard of light'
subStoryD (16) := 'The trio finds the exit, one hour into the hall'
subStoryC (16, 0) := 1868
subStoryC (16, 1) := 573
subStoryN (17) := 'VII - I. Mantlepiece'
subStoryD (17) := 'A large room with statues.. that are alive'
subStoryC (17, 0) := 2072
subStoryC (17, 1) := 513
subStoryN (18) := 'VII - I A. E-5 10x'
subStoryD (18) := 'Dragon uncovers a bomb inside a statue. 10 minutes to diffuse!'
subStoryC (18, 0) := 2072
subStoryC (18, 1) := 611
subStoryN (19) := 'VII - II. Failed journey'
subStoryD (19) := 'Another hall connected to the center room leads to bodies'
subStoryC (19, 0) := 2163
subStoryC (19, 1) := 513
subStoryN (20) := 'VII - II A. E-5 11x'
subStoryD (20) := 'A second bomb.. diffuse or watch it blow?'
subStoryC (20, 0) := 2163
subStoryC (20, 1) := 611
subStoryN (21) := "VIII - I. June"
subStoryD (21) := 'A clone of July claims to be the real July. Who can you trust?'
subStoryC (21, 0) := 2341
subStoryC (21, 1) := 524
subStoryN (22) := 'VIII - II. Red'
subStoryD (22) := 'Just as the trio reach the top of the palace, a second Blue steps out of the shadows'
subStoryC (22, 0) := 2445
subStoryC (22, 1) := 552
subStoryN (23) := 'IX - I. System break'
subStoryD (23) := 'The system begins malfunctioning, indicating the world is not real'
subStoryC (23, 0) := 2630
subStoryC (23, 1) := 507
subStoryN (24) := 'IX - II. Proliferation'
subStoryD (24) := 'Multiple Dragons attempt to kill the trio, no emotion on their faces'
subStoryC (24, 0) := 2687
subStoryC (24, 1) := 633
subStoryN (25) := 'IX - III. Extinguish'
subStoryD (25) := 'Dragon wakes up and sees that she is alone'
subStoryC (25, 0) := 2732
subStoryC (25, 1) := 545
%%%%%%%%%%%%%%%%%%% EXCURSION
excursionN (0) := 'I. "Whispers in the dark"'
excursionD (0) := 'Investigate the source of the faint and eerie sound'
excursionC (0, 0) := 524
excursionC (0, 1) := 306
excursionN (1) := 'II. Name'
excursionD (1) := 'Description Here'
excursionC (1, 0) := 649
excursionC (1, 1) := 269
excursionN (2) := 'III. Name'
excursionD (2) := 'Description Here'
excursionC (2, 0) := 819
excursionC (2, 1) := 144
excursionN (3) := 'III A. Name'
excursionD (3) := 'Description Here'
excursionC (3, 0) := 943
excursionC (3, 1) := 143
excursionN (4) := 'IV. Name'
excursionD (4) := 'Description Here'
excursionC (4, 0) := 851
excursionC (4, 1) := 334
excursionN (5) := 'V. Name'
excursionD (5) := 'Description Here'
excursionC (5, 0) := 919
excursionC (5, 1) := 244
excursionN (6) := 'VI. Name'
excursionD (6) := 'Description Here'
excursionC (6, 0) := 967
excursionC (6, 1) := 352
excursionN (7) := 'VII. Name'
excursionD (7) := 'Description Here'
excursionC (7, 0) := 1148
excursionC (7, 1) := 254
excursionN (8) := 'VIII. Name'
excursionD (8) := 'Description Here'
excursionC (8, 0) := 1205
excursionC (8, 1) := 194
excursionN (9) := 'VIII A. Name'
excursionD (9) := 'Description Here'
excursionC (9, 0) := 1333
excursionC (9, 1) := 195
excursionN (10) := 'VIII B. Name'
excursionD (10) := 'Description Here'
excursionC (10, 0) := 1446
excursionC (10, 1) := 195
excursionN (11) := 'IX. Name'
excursionD (11) := 'Description Here'
excursionC (11, 0) := 1246
excursionC (11, 1) := 330
excursionN (12) := 'X. Name'
excursionD (12) := 'Description Here'
excursionC (12, 0) := 1469
excursionC (12, 1) := 328
excursionN (13) := 'XI. Name'
excursionD (13) := 'Description Here'
excursionC (13, 0) := 1548
excursionC (13, 1) := 302
excursionN (14) := 'XII. Name'
excursionD (14) := 'Description Here'
excursionC (14, 0) := 1730
excursionC (14, 1) := 296
excursionN (15) := 'XIII. Name'
excursionD (15) := 'Description Here'
excursionC (15, 0) := 1800
excursionC (15, 1) := 233
excursionN (16) := 'XIV. Name'
excursionD (16) := 'Description Here'
excursionC (16, 0) := 1856
excursionC (16, 1) := 330
excursionN (17) := 'XV. Name'
excursionD (17) := 'Description Here'
excursionC (17, 0) := 2101
excursionC (17, 1) := 233
excursionN (18) := 'XVI. Name'
excursionD (18) := 'Description Here'
excursionC (18, 0) := 2329
excursionC (18, 1) := 329
excursionN (19) := 'XVII. Name'
excursionD (19) := 'Description Here'
excursionC (19, 0) := 2378
excursionC (19, 1) := 180
excursionN (20) := 'XVII A. Name'
excursionD (20) := 'Description Here'
excursionC (20, 0) := 2492
excursionC (20, 1) := 181
excursionN (21) := 'XVII B. Name'
excursionD (21) := 'Description Here'
excursionC (21, 0) := 2660
excursionC (21, 1) := 183
excursionN (22) := 'XVII Z. Name'
excursionD (22) := 'Description Here'
excursionC (22, 0) := 2657
excursionC (22, 1) := 285
excursionN (23) := 'XVIII. Name'
excursionD (23) := 'Description Here'
excursionC (23, 0) := 2433
excursionC (23, 1) := 298
excursionN (24) := 'XIX. Name'
excursionD (24) := 'Description Here'
excursionC (24, 0) := 2764
excursionC (24, 1) := 337
